# Sample workflow for building and deploying a Docusaurus site to GitHub Pages
name: Deploy Docusaurus with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch & contrib subdirectory
  push:
    paths:
      - 'contrib/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  branch-build:
    if: ${{ github.ref != 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000
      # ðŸ‘‡ Build steps
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Compile code to create pages
        working-directory: contrib/docs
        run: |
          pip install jinja2
          python compile_docs.py
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          # The action defaults to search for the dependency file
          # (package-lock.json or yarn.lock) in the repository root, and uses
          # its hash as a part of the cache key.
          # https://github.com/actions/setup-node#caching-packages-dependencies
          cache-dependency-path: "./contrib/docs/package-lock.json"
      - name: Install dependencies
        working-directory: contrib/docs
        run: yarn install --frozen-lockfile --non-interactive
      - name: Build
        working-directory: contrib/docs
        run: yarn build
      # ðŸ‘† Build steps
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000
      # ðŸ‘‡ Build steps
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Compile code to create pages
        working-directory: contrib/docs
        run: python compile_docs.py
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          # The action defaults to search for the dependency file
          # (package-lock.json or yarn.lock) in the repository root, and uses
          # its hash as a part of the cache key.
          # https://github.com/actions/setup-node#caching-packages-dependencies
          cache-dependency-path: "./contrib/docs/package-lock.json"
      - name: Install dependencies
        working-directory: contrib/docs
        run: yarn install --frozen-lockfile --non-interactive
      - name: Build
        working-directory: contrib/docs
        run: yarn build
      # ðŸ‘† Build steps
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # ðŸ‘‡ Specify build output path
          path: contrib/docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
